//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gmail { get; set; }
        public string password { get; set; }
        public string semester { get; set; }
        public string shift { get; set; }
        public string dep { get; set; }
        public string gender { get; set; }
    }
}
